### PR TITLE
Updated runtime object from API page

### PR DESCRIPTION
**Pull request by mumblepins**
Added `rawTemperature` and `showIconMode` which was recently added to the API.

### CODE REVIEW

**Review by jefwu72 — APPROVED** [review]
agreed with the updates.  it is necessary to get Pyecobee API working again.

**Comment by jefwu72** [comment]
can this "fix" merge into the main branch and request a patch release.

**Comment by tripzero** [comment]
bump. This should be merged.

**Review by tripzero — APPROVED** [review]

**Comment by sherif-fanous** [comment]
1.3.0 released with lots of changes including the above.

**Pull request closed without merging**
